### ISSUE TITLE
bindings with type-safety using interfaces

### ISSUE THREAD

**Issue by haseebrabbani** [jeffijoe/awilix#135]
Hey man, first of all love your work on this library! I have been using it with great joy in my projects 😃

I had a Typescript question: is it possible to get type-safety when declaring my bindings? Ideally, I would be binding to an interface. Let's say I have the following:

```
interface UserRepository {
    getUser(id): Promise<User>
}

class InMemoryUserRepository implements UserRepository {
    async getUser(id): Promise<User> {
        ...
    }
}

class SomeService {
    constructor(userRepo: UserRepository) {
        ...
    }
}
```

I want to be able to declare the binding from the interface to the implementation with type-checking like so: `UserRepository: asClass(InMemoryUserRepository)`. From what I understand, currently I would have to bind the implementation to the `userRepo` keyword instead of the interface. Is there a way to achieve this?

**Comment by jeffijoe** [comment]
Thanks for the kind words!

I'm afraid not because TypeScript is compile-time only and JavaScript has no notion of interfaces.

You are going to have to rely on your configuration being correct.

**Comment by haseebrabbani** [comment]
Appreciate the quick response 🙂just wanted to probe a bit more: I understand that JS has no interfaces, but if I'm declaring my bindings using TS, shouldn't it be able to get the safety checks?

**Comment by jeffijoe** [comment]
No problem! 😄

You only get the type checking when you yourself are calling things. There's nothing stopping you from injecting a `Foo` where you declare in TS that you expect a `Bar`, if I just do `foo as any`.

Because there's no type info from TS made available to JS, Awilix can't bind your interface to implementations and resolve based off that, like you're probably used to from C# or Java.

Awilix uses the parameter name declared in your function (by parsing it) and matches it to what you registered. It's up to you to make sure you only register compatible implementations.
