### ISSUE TITLE
Registering Mongoose Model in Correct Way

### ISSUE THREAD

**Issue by KrGyan** [jeffijoe/awilix#142]
const mongoose = require("mongoose");

const { Schema } = mongoose;

const auditLogsSchema = new Schema(
    {
        application_id: String,
        type: String,
        
    },
    { strict: false }
);

module.exports = () => mongoose.model("applicationauditlog", auditLogsSchema);

I have my schema which I am registering as auto register Mode:

 this.container.loadModules(["models/**/*.js"], {
                formatName: "camelCase",
                resolverOptions: {
                    lifetime: Lifetime.SINGLETON,
                    register: awilix.asValue
                }
            });

When using in service, I am getting below issue:
**TypeError: _this.schema.find is not a function**
export default class sampleRepoService {
    constructor({ applicationauditlog }) {
        this.schema = applicationauditlog;
    }

    async getSampleData() {
        return new Promise((resolve, reject) => {
            try {
               
                this.schema.find({}).limit(1).exec((err, result) => {
                        if (err) {
                            
                            return reject(err);
                        } else {
                            if (result.length == 0) {
                                
                                return reject(err);
                            } else {
                                appLogger.info(result, "End of helper: AuditsHelper, Method: getAudits");
                                return resolve(result);
                            }
                        }
                    })
            } catch (err) {
                console.log(err);
                reject(err);
            }
        });
    }

    getSample() {
        return "test";
    }
}

**Comment by jeffijoe** [comment]
Use `asFunction` instead of `asValue` — you are exporting a `() => ` so that's what gets registered when you use `asValue`. If you use `asFunction`, the function gets called.

**Comment by KrGyan** [comment]
That throws an error which I was expecting while compiling: OverwriteModelError: Cannot overwrite `applicationauditlog` model once compiled

**Comment by jeffijoe** [comment]
You can try using `asValue` and then instead of `module.exports = () => mongoose...` do `module.exports = mongoose...`

**Comment by KrGyan** [comment]
That still throws same error...

**Comment by jeffijoe** [comment]
That sounds like a mongoose issue then. `loadModules` just uses `require`, and it seems like the issue is happening at the call to `mongoose.model`, which isn't using anything Awilix-specific (it's just an export).

I don't use Mongoose, but I think @JamieCorkhill does.

**Comment by JamieCorkhill** [comment]
@KrGyan Why do you export the model as a factory function? I export the model as-is:

```javascript
const mongoose = require("mongoose");

// Define the schema.
const auditLogsSchema = new mongoose.Schema({
    application_id: String,
    type: String,
}, {
    strict: false 
});

// Define instance/static schema methods here.

// Create the model.
const AuditLogs = mongoose.model("applicationauditlog", auditLogsSchema);

// Export the model.
module.exports = AuditLogs;
```
Then, in the Awilix container, I load the Model as follows:
```javascript

// Load modules for Models.
container.loadModules([
    [
        '../models/**/*.js', 
        {
            register: awilix.asValue,
            lifetime: awilix.Lifetime.TRANSIENT
        }
    ],
], {
        cwd: __dirname,
        formatName: name => `${name.charAt(0).toUpperCase()}${name.substring(1)}`
});
```
Note also that it's convention to define your model names in PascalCase (UpperCamelCase) since they are indeed instantiable classes - i.e, you have constructor invocation with `new`.

Do you have reproduction you can create for me or should I make one myself so that I can help further?

**Comment by JamieCorkhill** [comment]
@KrGyan 

Also, in your service, and while this won't help with your issue, functions marked `async` will automatically return a promise, so you don't need to `return new Promise((resolve, reject) => {});` inside. The point of `async` is to permit you to use `await`, which you don't do. You can still keep your `try/catch` block and just re-throw any errors in `catch` to let them bubble up, and then whatever calling code uses your Service can get the result back as a promise.

@jeffijoe I believe that's correct but do you want to check me on that?

@KrGyan I'm trying out a repro I made based on the information you provided here. I'll get back to you.

**Comment by JamieCorkhill** [comment]
@KrGyan I created an isolated reproduction ready to clone that demonstrates Mongoose Models working well with Awilix. A MongoDB Server will have to be running, of course. It also shows more proper usage of `async`/`await`.

Repository: https://github.com/JamieCorkhill/AwilixWithMongooseModel

@jeffijoe I don't think there is anything wrong with Awilix, but we can't see enough of @KrGyan's set up to tell. Some things from his example code don't make sense, including why `container` is available on `this` in whatever file he is using to create the container. Additionally, he is using `module.exports` for his model but `export default` for the service, so I suppose Babel is being used? @KrGyan I'm happy to help further, but can you explain any of the discrepancies I listed above.

Also, exporting the model as a factory function and registering it in the container with `awilix.asFunction` works fine for me too. I'm using the default `TRANSIENT` lifetime, although `SINGLETON` works fine as well.

**Comment by jeffijoe** [comment]
Yeah I figure it’s something else in his setup.

Thanks @JamieCorkhill for your input!

**Comment by KrGyan** [comment]
@JamieCorkhill  thanks for the repo. It seems that babel is the issue. Your view pls

@jeffijoe  .. thanks for inputs

**Comment by JamieCorkhill** [comment]
@KrGyan 

> Your view pls

I'm apologize, I'm not sure I understand what you mean.

**Comment by KrGyan** [comment]
@JamieCorkhill  - I am using babel in my step up . Should that be a problem ?

**Comment by JamieCorkhill** [comment]
@KrGyan Perhaps it has to do with how Babel is transpiling `export default` behind the scenes. Awilix might not be able to import your modules/dependencies. 

Can you show your package.json file and your .babelrc file?

**Comment by jeffijoe** [comment]
Awilix works with Babel, thats not it. It sounds like a Mongoose-related issue.

**Comment by JamieCorkhill** [comment]
@KrGyan Is there anything you are able to apply from the repository that I sent you.

@jeffijoe It sounds like Awilix is actually resolving the dependency correctly. OP is saying that the error is `TypeError: _this.schema.find is not a function`. While I don't get the underscore, I would take that to say that `find` is not a function available on `schema`, not that `schema` is undefined, and since `schema` is the name of the instance variable on the class which gets set to the model injected by Awiix, then Awilix is doing its job. So, as you say, it would have to be Mongoose.

**Comment by jeffijoe** [comment]
That error occurred because he was injecting the factory using asValue.

**Comment by JamieCorkhill** [comment]
@jeffijoe - Ah, so `asValue` was injecting the entire function so `schema` would have been the actual function. Do I have that right?

**Comment by jeffijoe** [comment]
Yep.

**Comment by KrGyan** [comment]
Thanks @jeffijoe @JamieCorkhill. 

It seems to be mongoose level issue. 

@JamieCorkhill - As requested:
.bebelrc
{
    "presets": [
        ["@babel/preset-env"]
    ],
    "plugins": [
        ["@babel/plugin-proposal-export-default-from"]
    ]
  }

package.json :

"start": "babel-node app.js",

**Comment by JamieCorkhill** [comment]
@KrGyan Thank you.

1. I agree that it is a Mongoose issue.
2. Thanks for the .babelrc file.
3. Your package.json file should include a little bit more than that, but I don't think I need it.
4. You can format code in Markdown by placing it between a pair of three ticks.

It's difficult to help you because we can't see everything that is going on. Something else must be awry in your codebase that is causing an issue that you haven't reproduced here.

So, firstly, was there anything you were able to take away from the Repository that I sent you? Was there anything you were able to apply to your codebase to attempt to fix the issue? It's very possible to use Mongoose with Awilix, and the repo I sent should give you some idea how.

If not, can you produce a standalone but isolated reproduction of the issue you are having? I don't know how big or small your project is, but could you put to together a Repository containing as little as required to reproduce the error you are encountering? At this point, that'll be the best way to help you. If you're not comfortable posting it to GitHub, you can email me a ZIP file of your project, just make sure your `node_modules` folder is ***not*** included in that archive. With that said, I'd much prefer a clonable repository instead of an email.

As I said, I'm really happy to help you, but I need a little more information to be able to do that.

Thanks,
Jamie

**Comment by KrGyan** [comment]
@jeffijoe  @JamieCorkhill  . Thanks for your help. 

I am able to use mongoose. It was setup issues, I was by mistake binding the same model two times.

**Comment by JamieCorkhill** [comment]
@KrGyan Well done, glad you figured it out.
