### ISSUE TITLE
A callback or signal to indicate that a service is ready now to be used by other services

### ISSUE THREAD

**Issue by agarwalkartik** [jeffijoe/awilix#172]
If I have a service lets say **redis** and another lets say **user controller** which depends on redis and I want **use controller** top be started only if **redis** is properly started how can I achieve this in awilix? 

Its conceptually a way for each service to tell the container that it is now ready to be used by other services, I find this quite useful in case of services which make third party connections like db services. Can this be a new feature request?

**Comment by jeffijoe** [comment]
That would mean making the container do more than just composition, and so the gap between being able to use vanilla DI vs using a container grows, which is not a good sign.

Most connections handle the `connect()` part in their API though, for example I can create a `knex()` instance without awaiting it, it automatically connects on the first query. Strive for those kinds of APIs. Otherwise, I would suggest connecting at startup and registering the connection.

**Comment by agarwalkartik** [comment]
>  I would suggest connecting at startup and registering the connection.

This seems to be a better option as most of the libraries (in my limited knowledge) do not function like `knex`.
