### ISSUE TITLE
Resolving promises when registering

### ISSUE THREAD

**Issue by suchy** [jeffijoe/awilix#175]
Hi ;-)

DI concept is a new thing for me so experimenting a little bit.

Below is more o less structure of my application.

Looks kind of ok but I think I'm doing something wrong passing `Promise` "down". Connection to mongo is a promise, because of that selecting collection is a promise, because of that repository is a promise, because of that service is a promise. 

Is there any chance to stop "pushing promise down" and for example resolve it when registering db connection and then cach only resolved value and pass it forward?

Maybe current implementation is ok but all those promises look suspiciously for me.

Thanks for your patients ;-)

`container.js`:
```
import { asFunction, createContainer } from 'awilix';

import Logger from './helpers/logger';

import DbConnection from './helpers/db-connection';

import Collection from './collection';

import Repository from './repository';

import Service from './service';


const container = createContainer();

container.register({
  logger: asFunction(Logger),


  DbConnection: asFunction(DbConnection).singleton(),

  Collection: asFunction(Collection),

  Repository: asFunction(Repository),

  Service: asFunction(Service),
});

export default container;
```

`db-connection.js`:
```
import config from 'config';
import mongodb from 'mongodb';

const { database, url } = config.get('mongo');

let db;

export const DbConnection = async ({ logger }) => {
  if (!db) {
    const client = await mongodb.MongoClient.connect(url, {
      useUnifiedTopology: true,
      useNewUrlParser: true
    });

    logger.info(`MongoDB connected`);

    db = client.db(database);
  }

  return db;
};
```

`collection.js`:

```
export const Collection = ({ DbConnection }) => (
  collectionName: string
) => DbConnection.then((db) => db.collection(collectionName));
```

`repository.js`:

```

export const Repository = ({ Collection } ) => async (collectionName: string) => {

    const collection = await Collection(collectionName);

    const repository = {
      find: () => {},
    };

    return repository;
  };
```

`service.js`

```

const Service = async ({ logger, Repository }) => {
  const repository = Repository('service-name');

  return {
    doSomeMagic: () => {}
  };
};

export default Service;
```

**Comment by JamieCorkhill** [comment]
I haven't used the MongoDB Native Driver before, but I think you could `await` the resolution of your connection attempt **prior** to creating the container, and then you could just inject the resulting connection/client instead of your `DbConnection` factory function. This would save you from having to pass down and call the `async DbConnection` function all the way through the tree for each DB operation in a new scope.

So at this point, now your collection getter function can stay synchronous since it just gets the plain, already resolved client injected in and because, looking at Mongo's API reference, `db.collection()` is sync as well, so both your service and your repo factories now won't don't need to be `async` because, again, that `Collection` factory you have can do everything synchronously.

This was proposed by @jeffijoe in #12: https://github.com/jeffijoe/awilix/issues/12#issuecomment-280912922

It's probably a good idea to take a look at his implementation. It involves wrapping your container creation logic in an asynchronous container configuration factory function. 

> Is there any chance to stop "pushing promise down" and for example resolve it when registering db connection and then cach only resolved value and pass it forward?

The above, I believe, is exactly what you're looking for.

**Comment by suchy** [comment]
Works perfectly, thanks! 🍕

**Comment by JamieCorkhill** [comment]
You're welcome, happy to help.
