### ISSUE TITLE
[vite] - No matching export for import pathToFileUrl

### ISSUE THREAD

**Issue by jdmorlan** [jeffijoe/awilix#232]
I'm using [ViteJS](https://vitejs.dev/) as the build tool for a React application. When I try to run the vite dev server I get the error referenced in the title above. I'm not very well versed in the workings of awilix, but attempted to Google for that error. I was able to find a couple of things about `loadModules` and Windows tests, but didn't seem to match this issue. 

I setup a [repo](https://github.com/jdmorlan/vite-awilix) that isolates vite, awilix and [jishida/react-awilix](jishida/react-awilix).  I'm more than willing to do more investigating, but I'm kind of stuck with what to attempt next. Any help or advice would be greatly appreciated. 

## Error Message

<img width="1311" alt="error" src="https://user-images.githubusercontent.com/615215/110134366-ebd16d00-7d92-11eb-9213-e63d2017a441.png">

**Comment by jeffijoe** [comment]
You need to configure your build tool to use [the browser build](https://github.com/jeffijoe/awilix#universal-module-browser-support).

**Comment by simonvizzini** [comment]
Hi @jdmorlan, I know it's been a while when you asked this question but I'm facing the same issue. Have you ever figured out how to properly configure Vite to make it work with Awilix? I know that Vite is using esbuild under the hood and esbuild has a [platform](https://esbuild.github.io/api/#platform) option which can be set to `node` or `browser`, but it doesn't seem to be directly exposed in the Vite config. Closes thing I have found is the [optimizeDeps.esbuildOptions](https://vitejs.dev/config/#optimizedeps-esbuildoptions) Vite option which does exposes the platform option from esbuild, but setting it to `browser` didn't change anything, Vite is still using the node-only `lib/awilix.module` bundle instead of the `lib/awilix.browser` bundle.

Only workaround I found so far is to directly import the browser bundle in my code. Typescript then complains but at least it is still getting built.

**Comment by downace** [comment]
I've faced similar issue.

Added alias in my `vite.config.ts` to make it work:

```
export default {
  resolve: {
    alias: {
      'awilix': 'awilix/lib/awilix.browser'
    }
  }
}
```

Maybe it should be noted in the docs...

**Comment by jeffijoe** [comment]
I would think it's something that should be fixed on Vite's side? Webpack resolves the browser build by default just fine.

**Comment by downace** [comment]
> I would think it's something that should be fixed on Vite's side? Webpack resolves the browser build by default just fine.

Ah, I think I got it. Found this open issue in Vite repo: https://github.com/vitejs/vite/issues/7576. Looks like the problem is the same.
