### ISSUE TITLE
Inject module descriptor?

### ISSUE THREAD

**Issue by bosconian-dynamics** [jeffijoe/awilix#243]
I would like to automatically configure a logger instance/context for each module added to a container via `loadModules()` - more specifically, by adding the module name to a Pino child logger - but I do not see a way to access module information from within a registered resolver.

Is there some way to accomplish this which I am overlooking? If not, might it be reasonable for Awilix to locally inject and/or provide the module descriptor as an argument to `InjectorFunction`?

This is roughly what I have in mind:
```typescript
const container = awilix.createContainer();
const logger = pino();

container.register( {
    container_name: asValue( 'root' ),
    logger: asFunction(
        ( { container_name, module_name } ) => logger.child( { container: container_name, module: module_name } )
      )
      .inject(
        ( container, module ) => ( { module_name: module.name } )
      )
} );
```
I am really loving Awilix so far - thank you for your time and effort :)

**Comment by jeffijoe** [comment]
This is currently not possible because the `loadModules` feature is just a convenience method to register a bunch of stuff based on conventions. Because of that, we can't pass in module descriptors since if you were using plain `.register` they would not be available.

With that said, nothing is stopping you from using `listModules` and then registering them in the container however you like.

I would recommend that each module receive a `createLogger` factory to create a logger instance for that module. It's more explicit which I view as a good thing. I try to keep the dependency injection container magic to a minimum.

**Comment by bosconian-dynamics** [comment]
Fair on all accounts - I really appreciate the input!

I will play with both of the mentioned implementations - the `createLogger` factory does sound the most reasonable
