### ISSUE TITLE
How to unregister a dependency from the container?

### ISSUE THREAD

**Issue by jlenon7** [jeffijoe/awilix#338]
Is it possible to unregister a dependency from the container from its name/key? Or even replace the already registered dependency by another one (I've tried this and does not work)?

### Use case

I'm trying to change the registered dependency in runtime when running a “testing” environment. I would like to be able to replace the already registered dependency by a mock.

**Comment by jeffijoe** [comment]
You can replace a registration simply by calling register again with the same key. I do this for testing as well.

**Comment by jlenon7** [comment]
Just saw that it doesn't work with `singleton` dependencies only:

```typescript
import { createContainer, asFunction } from 'awilix'

const container = createContainer()

container.register('foo', asFunction(() => 'bar').singleton())
console.log(container.resolve('foo')) // bar

container.register('foo', asFunction(() => 'mock').singleton())
console.log(container.resolve('foo')) // bar
```

**Comment by jeffijoe** [comment]
You have to replace it before the first resolve.

**Comment by jlenon7** [comment]
What do you mean? Could you give a code example please?

**Comment by jlenon7** [comment]
Is there any possibility to get the same behavior of my example no matter the registration type? Or maybe a way to unregister a dependency?

I would be happy to help with that implementation if you think it is feasible.

**Comment by jeffijoe** [comment]
The issue with what you are asking is that if you have other modules that depend on `foo`, and those modules have already been resolved, then even after replacing the registration, those modules would still have references to old instances of `foo`.

You should either restructure your code, or resort to some less-than-ideal hackery such as wrapping it in a proxy and then perform your replacement using whatever mechanism you implement for it, or resorting to manually clearing the cache `container.cache.delete('foo')` however I would advise against it due to what I mentioned above about other modules keeping their own reference to the value from initial resolve.

A simple pattern for testing is to have a `createApplication` function that wraps your app bootstrap which supports passing in a container that you get from `configureContainer`. Then for tests:

```ts
const container = configureContainer()
container.register({ foo: asValue(fakeFoo) })
const app = createApplication(container)
```

**Comment by jlenon7** [comment]
Got it, thanks for the tips.
