### ISSUE TITLE
[DISCUSSION] Change default injection mode to `CLASSIC`?

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/awilix#68]
Since v2.0, Awilix has injected an ES6 `Proxy` which was used to resolve dependencies so we wouldn't have to use a shoddy regex to parse function signatures.

@cjhoward92 submitted PR #21 that added support for what is now referred to as `CLASSIC` injection mode, where—using a decent regex—the function signature was parsed to extract parameter names. 

It wasn't without its issues though, for example arrow functions were not that well supported (#30), and so I wrote a basic parser to replace the regex which has worked very well.

I have personally started using `CLASSIC` injection more, especially in TypeScript projects, and #59   added support for default parameters, making the parser even more tolerant of real-world code.

The parser runs **once per registration**, so runtime performance should actually be better than using the Proxy.

What do you guys think? Which injection mode do you use in your projects?

**Should we change the default to `CLASSIC`?**

_Note: this does not mean we're getting rid of `PROXY`, this is just about changing the default._

------

/cc @ddproxy @cjhoward92 @blove @cikasfm @Seldszar @niyoko @thisdotrob @mikhas-rock @leorossi @ith @Vincz @neerfri @ewrogers @dboune

**Comment by Seldszar** [comment]
As long the Proxy mode is still available, I'm totally OK.
And if, performance-wise, the classic mode is better, why not provide it by default, especially if the performances are better.

**Comment by jeffijoe** [comment]
@Seldszar yes, Proxy-mode will still be available: `createContainer({ injectionMode: InjectionMode.PROXY })` is all it takes.

**Comment by neerfri** [comment]
I can say for myself that the proxy injection is the reason I chose this library over all others.

I think the conceptual model of the proxy is simpler than the Classic model, especially when regex expressions are involved.
This comes very handy when you have async dependencies (aka providers) that you would like to trigger in a lazy way. Although I'm sure it would be possible in the Classic mode, it will probably be much more verbose and less obvious. for example:

```
// app.js
export default async function createApp(dependencies) {
  return {
    async getUser(id) {
      // Here we want to trigger the async dependency only when it's needed.
      const userService = await dependencies.userService;
      return userService.getUser(id);
    }
  }
}

// userService.js
export default async function creteUserService(dependencies) {
  // Here we want to trigger the async dependency when creating the userService.
  const db = await dependencies.db;
  const User = db.Model('User');
  return {
    getUser(id) { return User.find(id) }
  }
}
```

Regarding usage in TypeScript I think TypeScript's "idiomatic" way has become to use `InversifyJS`, I felt that `awilix`was the best option for people that prefer a more "functional" style.

**Comment by jeffijoe** [comment]
@neerfri AFAIK Inversify only supports classes, and you have to use special decorators + symbols that pollute your code with DI-specific fragments which I am not a fan of. Classic mode supports both classes and functional factories, the only difference is how dependencies are injected.

The regex is no longer used for parsing the signature, I've rewritten the [tokenizer](https://github.com/jeffijoe/awilix/blob/v3/src/function-tokenizer.ts) + [parser](https://github.com/jeffijoe/awilix/blob/v3/src/param-parser.ts) for v3 to support very complex stuff like default parameter values that include templated strings, all without the user having to do a thing.

On another note, while it is true that Proxy mode enables your example (as well as circular dependencies), I can't recommend doing so. While I understand what `await dependencies.userService` does, it's not really _as_ obvious as passing in a built instance. **Factories** are good for these sorts of things, but I have yet to come up with a good API to make them seamless to use.

Here's an example I just wrote, it should work and give you the ability to use async factories using classic mode, in a more explicit way.

```js
// A resolver that returns a factory function.
const factory = (resolver) => ({
  resolve: container => () => container.build(resolver)
})

async function createUserService(lol) {
  // Some async stuff.
  await Promise.delay(1000)

  return {
    get: () => {/**/}
  }
}

function createApp(createUserService) {
  return {
    async getUser(id) {
      // More explicit that we're lazy-instantiating.
      return (await createUserService()).get(id)
    }
  }
}


async function main() {
  const container = createContainer({ injectionMode: InjectionMode.CLASSIC })
    .register({
      lol: asValue('haha'),
      createUserService: factory(asFunction(createUserService))
    })

  const run = container.build(createApp)
  await run()
}
```

Just to reiterate, **Proxy will still be available** if this proposal is implemented. 👍

**Comment by neerfri** [comment]
I understand we are talking ONLY about what the default is, no worries here :-)
The reason I find it interesting to discuss this is that I'm surprised that you feel it should be the default, given that the proxy mode was, in my opinion, the differentiating feature of this library to all the others I've seen. It is implemented in a simple and elegant way which keeps a readable codebase that's easy to contribute to and easy to chose to base your app on.

That being said I think it's important to hear what other people think.

Regarding your example, as I said, I'm sure it's possible, but at least for me it takes a while to understand what is happening here, it's very easy to make mistakes that will make `createUserService()` not act as a singleton (you cover it, but you are the author of this lib, obviously you understand it deeply :-) )

To add to what I wrote earlier, I tend to stay away from usage of parsers on code (in JS), JavaScript is a language that does not provide us with a proper code-as-data model (in contrast to closure, elixir, erlang, ...) and we cannot access the AST of some code. The way it is handled in `InversifyJS` is by using TypeScript's embedded metadata (with `emitDecoratorMetadata`), so you annotate the dependency argument with a string in an explicit way, which I believe is the right way to go in such cases, I understand your argument for not liking it, but I would argue that annotating your code with information that is tied to your DI model is actually a good thing, it makes everything explicit and non-magical (or at least less magical).

There's currently a proposal for adding a similar metadata support for JS but as far as I can see it's still in early stages: https://rbuckton.github.io/reflect-metadata/ (with an early attempt of implementation in https://www.npmjs.com/package/reflect-metadata).
This is not targeting arguments yet (one can still decorate the whole function/class with the proper info for it's args)

Recall the problems people had with angular when it used to parse your dependencies using a regex (or maybe a parser), which is why the recommended way was to also add an array of strings that represents your dependencies:
```
angular.module('MyApp.core').factory('core.Blog.Post', [
  // You had to specify this as a string and match it in the position
  // of the args if you wanted to use minification...
  'RailsResource' 
  (RailsResource) => { /* factory returned value */ }
])
```

Since you are only talking about changing the default behavior it's not a big deal anyways.

**Comment by jeffijoe** [comment]
@neerfri Yeah the angular approach isn't that user-friendly haha :P

> It is implemented in a simple and elegant way which keeps a readable codebase that's easy to contribute to and easy to chose to base your app on.

Thanks! 😄 Actually the ugliest part about the codebase right now is handling the various Symbols that are used by tools like `console.log` and generators.

We can both agree that parsers are not exactly the stuff of beauty, but it's been hidden away and is also very well tested, so it's way more reliable than any regex could ever be, so you shouldn't worry too much about that. ;) Even if an edge case does pop up, I'll be sure to fix it. Writing parsers have sorta become a hobby of mine, hehe.

![image](https://user-images.githubusercontent.com/2505474/33516117-77c06214-d76d-11e7-8bee-5bca6976e0e7.png)
 
As for minification, you are absolutely right, that's one use case where Classic won't work and Proxy would save the day.

**Comment by jeffijoe** [comment]
@neerfri @Seldszar I've given it a lot of thought, and I think @neerfri makes a very valid point regarding minification issues. I just added official support for running Awilix in the browser, and if I change the default injection mode to `CLASSIC`, that will likely screw things up for newcomers who might not have gotten the note.

By actively switching to `CLASSIC`, we can assume you know what it is, and have therefore heeded the warning.
