### ISSUE TITLE
Use with Jest

### ISSUE THREAD

**Issue by zadigus** [jeffijoe/awilix#96]
Hi, 
I have never used Awilix yet but I am considering the idea. I invested some time trying to understand InversifyJS and, though it seems to be pretty cool, I kind of find it a bit overkill. 
I am currently developping a nodejs application which I write in Typescript and which I test with Jest. One problem I am encoutering with InversifyJS is that it doesn't seem to support automatic mocks (https://jestjs.io/docs/en/es6-class-mocks). I could circumvent that problem by just using mock functions but because Jest is providing us with that nice automatic class mocks feature, I would like to use it. 
The problem I have when using InversifyJS and Jest is that InversifyJS introduces decorators and `jest.mock` gets rid of them so that the mocked class doesn't satisfy the Inversify definition anymore.
Is this issue also occuring with Awilix?
Cheers

**Comment by jeffijoe** [comment]
When you are using constructor injection which Awilix makes you use, you don't need to use automatic mocks in Jest.

If you do use automatic mocks, it all depends on the code that Jest generates for them. If they generate a class with a constructor function that takes no arguments and does nothing with the arguments, then there should be no problem.

But just to reiterate, IMO automatic mocks are a tool designed for users who are unable to use DI. Since you are evaluating Inversify and Awilix, you do not fall under that category. 😄 

To illustrate, imagine this being your module:

```ts
interface IPrinter {
  print(msg: string): void
}

class Greeter {
  constructor(private printer: IPrinter) {}

  greet(name: string) {
    this.printer.print(`Hello ${name}!`)
  }
}
```

This is how you would test it in Jest.

```ts
test('Greeter calls printer with correct argument', () => {
  const printerMock = {
    print: jest.fn()
  }

  const greeter = new Greeter(printerMock)
  greeter.greet('Zadigus')
  
  expect(printerMock.print).toHaveBeenCalledWith('Hello Zadigus!')
})
```

Notice how I didn't even use Awilix here. The container is not needed when doing isolated unit tests.

One of the core philosophies of Awilix is that your business code should not smell of your DI library, and you should not need to fiddle with DI container settings when writing simple unit tests.

Hope this helps. 😄

**Comment by jeffijoe** [comment]
@zadigus does this answer your question? 😄

**Comment by zadigus** [comment]
@jeffijoe sorry for the delay, I've had a short holiday in-between. I wasn't expecting such a quick answer here!

So yes, that does answer my question. What I don't understand in your answer is why you suppose that automatic mocks are used by people that don't use DI. In Jest, an automatic mock can be built from an interface and reduces drastically your typing as you don't need to write 

```
export default class MyClass implements MyInterface {
  myMethod = jest.fn();
}
```

Instead of that, you just take the automatic mock directly and pass it as your interface's concretion. But it's a detail. In the end it's a matter of taste I guess. 

Thank you for your support on that!

**Comment by jeffijoe** [comment]
AFAIK auto mocks affect the entire file so you can't mix and match between using a real implementation and a fake. But glad you got your answer 😄
